global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

#  - job_name: 'postgres'
#    static_configs:
#      - targets: ['postgres-master:5432']
#
#  - job_name: 'redis'
#    static_configs:
#      - targets: ['redis:6379']
#
  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'appointment-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['appointment-service:3003']

  - job_name: 'config-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['config-service:3002']

  - job_name: 'queue-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['queue-service:3004']

  - job_name: 'notification-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['notification-service:3005']

  - job_name: 'statistics-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['statistics-service:3006']

  - job_name: 'ai-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['ai-service:3007']